// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 MikeFox303

export const printerSetupCopy = {
  en: {
    title: 'Printer connections',
    subtitle: 'Add Bambu LAN or Klipper/Moonraker printers directly from FoxForge.',
    configured: 'Configured printers',
    noConfigured: 'No printers are configured yet.',
    add: 'Add printer',
    kind: 'Connection type',
    bambu: 'Bambu Lab (LAN mode)',
    moonraker: 'Klipper / Moonraker',
    printerId: 'Printer ID',
    printerIdHint: 'Stable local ID, for example ender-ke.',
    bambuIdentityHint: 'FoxForge creates the stable local ID automatically from the Bambu serial number.',
    discovery: 'Find Bambu printers on the LAN',
    subnet: 'Subnet to scan',
    suggestedSubnets: 'Server-visible private networks',
    noSuggestedSubnets: 'No private LAN suggestion is visible to the FoxForge server. Enter the printer subnet manually.',
    subnetHint: 'Suggestions are private, bounded scan hints only. Docker/Umbrel may expose bridge networks, so verify the CIDR before scanning.',
    refreshSubnets: 'Refresh networks',
    loadingSubnets: 'Finding networks…',
    scan: 'Scan subnet',
    scanning: 'Scanning…',
    noCandidates: 'No Bambu candidates found. You can still enter the printer details manually.',
    candidateHint: 'Discovery is only a hint. FoxForge still verifies MQTT credentials before saving.',
    useCandidate: 'Use this printer',
    displayName: 'Display name',
    model: 'Model',
    modelPlaceholder: 'Select a model…',
    modelOther: 'Other / future model',
    modelCustom: 'Model name',
    vendor: 'Vendor',
    serial: 'Serial number',
    host: 'Printer IP / hostname',
    accessCode: 'LAN access code',
    baseUrl: 'Moonraker URL',
    apiKey: 'Moonraker API key (optional)',
    test: 'Verify connection',
    testing: 'Verifying…',
    save: 'Save and connect',
    saving: 'Saving…',
    reachable: 'Connection succeeded. FoxForge received a live printer state.',
    unreachable: 'Printer was not reachable',
    reconnect: 'Reconnect',
    reconnecting: 'Connecting…',
    remove: 'Delete',
    deleting: 'Deleting…',
    close: 'Close',
    refresh: 'Refresh',
    configuredSecret: 'credential saved',
    removeConfirm: 'Delete this printer from FoxForge? The physical printer is not modified.',
    deploymentError: 'Printer management is not enabled for this deployment. On Umbrel, update to a write-enabled FoxForge package and use the FoxForge app password in Operator access.',
    writesLocked: 'FoxForge write controls are locked. Open Operator access; on Umbrel use the FoxForge app password.',
    saveError: 'Unable to save printer.',
    deleteError: 'Unable to delete printer.',
    stepProvider: 'Provider',
    stepConnection: 'Connection',
    stepIdentity: 'Identity',
    stepVerify: 'Verify',
    providerHint: 'Choose the printer family first. Vendor-specific fields stay behind the provider boundary.',
    connectionHint: 'Discover a candidate or enter the connection details manually.',
    identityHint: 'Confirm the printer identity that FoxForge will use in the fleet.',
    verifyHint: 'Review the non-secret settings, verify the current payload, then save.',
    verifyRequired: 'Verify this exact configuration before saving. Any change after verification requires a new check.',
    verified: 'Current configuration verified. Save is enabled; FoxForge will still repeat backend preflight before persistence.',
    next: 'Next',
    back: 'Back',
  },
  ru: {
    title: 'Подключение принтеров',
    subtitle: 'Добавляйте Bambu LAN и Klipper/Moonraker прямо из FoxForge.',
    configured: 'Подключённые принтеры',
    noConfigured: 'Пока не настроено ни одного принтера.',
    add: 'Добавить принтер',
    kind: 'Тип подключения',
    bambu: 'Bambu Lab (LAN mode)',
    moonraker: 'Klipper / Moonraker',
    printerId: 'ID принтера',
    printerIdHint: 'Постоянный локальный ID, например ender-ke.',
    bambuIdentityHint: 'FoxForge автоматически создаёт постоянный локальный ID из серийного номера Bambu.',
    discovery: 'Найти принтеры Bambu в локальной сети',
    subnet: 'Подсеть для сканирования',
    suggestedSubnets: 'Приватные сети, видимые серверу',
    noSuggestedSubnets: 'FoxForge не видит подходящей приватной LAN-подсети. Укажите подсеть принтера вручную.',
    subnetHint: 'Подсказки — только приватные ограниченные диапазоны. Docker/Umbrel может показывать bridge-сети, поэтому проверьте CIDR перед сканированием.',
    refreshSubnets: 'Обновить сети',
    loadingSubnets: 'Поиск сетей…',
    scan: 'Сканировать подсеть',
    scanning: 'Сканирование…',
    noCandidates: 'Принтеры Bambu не найдены. Данные принтера можно ввести вручную.',
    candidateHint: 'Обнаружение только помогает заполнить форму. Перед сохранением FoxForge всё равно проверит MQTT и учётные данные.',
    useCandidate: 'Выбрать принтер',
    displayName: 'Название',
    model: 'Модель',
    modelPlaceholder: 'Выберите модель…',
    modelOther: 'Другая / будущая модель',
    modelCustom: 'Название модели',
    vendor: 'Производитель',
    serial: 'Серийный номер',
    host: 'IP / имя хоста принтера',
    accessCode: 'LAN access code',
    baseUrl: 'Адрес Moonraker',
    apiKey: 'API key Moonraker (необязательно)',
    test: 'Проверить подключение',
    testing: 'Проверка…',
    save: 'Сохранить и подключить',
    saving: 'Сохранение…',
    reachable: 'Подключение успешно. FoxForge получил актуальное состояние принтера.',
    unreachable: 'Не удалось подключиться к принтеру',
    reconnect: 'Переподключить',
    reconnecting: 'Подключение…',
    remove: 'Удалить',
    deleting: 'Удаление…',
    close: 'Закрыть',
    refresh: 'Обновить',
    configuredSecret: 'учётные данные сохранены',
    removeConfirm: 'Удалить этот принтер из FoxForge? Настройки физического принтера не изменятся.',
    deploymentError: 'Управление принтерами не включено в этой установке. В Umbrel обновите FoxForge до пакета с поддержкой записи и используйте пароль приложения FoxForge в разделе «Токен оператора».',
    writesLocked: 'Управление FoxForge заблокировано. Откройте «Токен оператора»; в Umbrel используйте пароль приложения FoxForge.',
    saveError: 'Не удалось сохранить принтер.',
    deleteError: 'Не удалось удалить принтер.',
    stepProvider: 'Провайдер',
    stepConnection: 'Подключение',
    stepIdentity: 'Идентификация',
    stepVerify: 'Проверка',
    providerHint: 'Сначала выберите семейство принтера. Поля конкретного производителя остаются внутри его провайдера.',
    connectionHint: 'Найдите принтер в сети или укажите параметры подключения вручную.',
    identityHint: 'Проверьте идентификацию принтера, которую FoxForge будет использовать в парке.',
    verifyHint: 'Проверьте параметры без секретов, выполните проверку текущей конфигурации и только затем сохраните её.',
    verifyRequired: 'Перед сохранением проверьте именно эту конфигурацию. Любое изменение после проверки требует повторной проверки.',
    verified: 'Текущая конфигурация проверена. Сохранение разрешено; перед записью FoxForge всё равно повторит backend preflight.',
    next: 'Далее',
    back: 'Назад',
  },
  uk: {
    title: 'Підключення принтерів',
    subtitle: 'Додавайте Bambu LAN і Klipper/Moonraker безпосередньо з FoxForge.',
    configured: 'Підключені принтери',
    noConfigured: 'Ще не налаштовано жодного принтера.',
    add: 'Додати принтер',
    kind: 'Тип підключення',
    bambu: 'Bambu Lab (LAN mode)',
    moonraker: 'Klipper / Moonraker',
    printerId: 'ID принтера',
    printerIdHint: 'Стабільний локальний ID, наприклад ender-ke.',
    bambuIdentityHint: 'FoxForge автоматично створює стабільний локальний ID із серійного номера Bambu.',
    discovery: 'Знайти принтери Bambu у локальній мережі',
    subnet: 'Підмережа для сканування',
    suggestedSubnets: 'Приватні мережі, видимі серверу',
    noSuggestedSubnets: 'FoxForge не бачить придатної приватної LAN-підмережі. Вкажіть підмережу принтера вручну.',
    subnetHint: 'Підказки — лише приватні обмежені діапазони. Docker/Umbrel може показувати bridge-мережі, тому перевірте CIDR перед скануванням.',
    refreshSubnets: 'Оновити мережі',
    loadingSubnets: 'Пошук мереж…',
    scan: 'Сканувати підмережу',
    scanning: 'Сканування…',
    noCandidates: 'Принтери Bambu не знайдено. Дані принтера можна ввести вручну.',
    candidateHint: 'Виявлення лише допомагає заповнити форму. Перед збереженням FoxForge усе одно перевірить MQTT та облікові дані.',
    useCandidate: 'Вибрати принтер',
    displayName: 'Назва',
    model: 'Модель',
    modelPlaceholder: 'Виберіть модель…',
    modelOther: 'Інша / майбутня модель',
    modelCustom: 'Назва моделі',
    vendor: 'Виробник',
    serial: 'Серійний номер',
    host: 'IP / ім’я хоста принтера',
    accessCode: 'LAN access code',
    baseUrl: 'Адреса Moonraker',
    apiKey: 'API key Moonraker (необов’язково)',
    test: 'Перевірити підключення',
    testing: 'Перевірка…',
    save: 'Зберегти й підключити',
    saving: 'Збереження…',
    reachable: 'Підключення успішне. FoxForge отримав актуальний стан принтера.',
    unreachable: 'Не вдалося підключитися до принтера',
    reconnect: 'Перепідключити',
    reconnecting: 'Підключення…',
    remove: 'Видалити',
    deleting: 'Видалення…',
    close: 'Закрити',
    refresh: 'Оновити',
    configuredSecret: 'облікові дані збережені',
    removeConfirm: 'Видалити цей принтер із FoxForge? Налаштування фізичного принтера не зміняться.',
    deploymentError: 'Керування принтерами не ввімкнене в цій інсталяції. В Umbrel оновіть FoxForge до пакета з підтримкою запису та використовуйте пароль застосунку FoxForge у розділі «Токен оператора».',
    writesLocked: 'Керування FoxForge заблоковано. Відкрийте «Токен оператора»; в Umbrel використовуйте пароль застосунку FoxForge.',
    saveError: 'Не вдалося зберегти принтер.',
    deleteError: 'Не вдалося видалити принтер.',
    stepProvider: 'Провайдер',
    stepConnection: 'Підключення',
    stepIdentity: 'Ідентифікація',
    stepVerify: 'Перевірка',
    providerHint: 'Спочатку виберіть сімейство принтера. Поля конкретного виробника залишаються в межах його провайдера.',
    connectionHint: 'Знайдіть принтер у мережі або введіть параметри підключення вручну.',
    identityHint: 'Перевірте ідентифікацію принтера, яку FoxForge використовуватиме у парку.',
    verifyHint: 'Перегляньте параметри без секретів, перевірте поточну конфігурацію і лише потім збережіть її.',
    verifyRequired: 'Перед збереженням перевірте саме цю конфігурацію. Будь-яка зміна після перевірки вимагає нової перевірки.',
    verified: 'Поточну конфігурацію перевірено. Збереження дозволено; перед записом FoxForge однаково повторить backend preflight.',
    next: 'Далі',
    back: 'Назад',
  },
} as const;

export type PrinterSetupCopy = { [K in keyof typeof printerSetupCopy.en]: string };
